// Generated by CoffeeScript 1.6.3
var Tyler, umd;

Tyler = function(data, element, options) {
  this.data = data;
  this.element = element;
  this.options = options;
};

umd = function(name, factory) {
  if (typeof exports === 'object') {
    return module.exports = factory;
  } else if (typeof define === 'function' && define.amd) {
    return define(name, factory);
  } else {
    return this[name] = factory;
  }
};

umd('Tyler', Tyler);
